export type Item = {
    article: string;
    name: string;
    image? : string;
    color: string;
    brand?: string;
    collection: string;
    base_material?: string;
    style: string;
    control?: string;
    view?: string;
    price?: number;
    weight?: number;
    width?: number;
    length?: number;
    height?: number;
}

export type ItemsFromServer = Item[];

export const ITEMS: ItemsFromServer = [
    {
      article: '101',
      name: 'Смеситель для кухни MEDICI Ripresa',
      image: 'https://boheme.su/upload/iblock/b29/m35xlw4na1x9itj8rh01pub69pqdnxij.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 23507.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 300.0,
    },
    {
      article: '102',
      name: 'Смеситель для кухни TRADIZIONALE ORO',
      image: 'https://boheme.su/upload/iblock/ed7/zvcd8nr6k5t2rfvh0lwog9uv18wmub4q.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 26118.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 300.0,
    },
    {
      article: '103',
      name: 'Смеситель для кухни TRADIZIONALE CHROMO',
      image: 'https://boheme.su/upload/iblock/0e4/q1pw1viya45hrdueoi0evkd6j3o631rg.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 20894.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 300.0,
    },
    {
      article: '111',
      name: 'Смеситель для кухни с краном MEDICI Ripresa',
      image: 'https://boheme.su/upload/iblock/97e/a3x6qrp37r25yiyus17p5kputgt5mmoh.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 25334.0,
      weight: 2400.0,
      width: 55.0,
      length: 230.0,
      height: 350.0,
    },
    {
      article: '112',
      name: 'Смеситель для кухни с краном TRADIZIONALE ORO',
      image: 'https://boheme.su/upload/iblock/1af/t3dtppc0tpy0n7qsbatvsh3mf18dxcxr.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 27869.0,
      weight: 2400.0,
      width: 55.0,
      length: 230.0,
      height: 350.0,
    },
    {
      article: '113',
      name: 'Смеситель для кухни с краном TRADIZIONALE CHROMO',
      image: 'https://boheme.su/upload/iblock/222/ettll7go61gxy07j7hv811knfo13c5j4.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 22357.0,
      weight: 2400.0,
      width: 55.0,
      length: 230.0,
      height: 350.0,
    },
    {
      article: '269',
      name: 'Смеситель напольный BRILLANTE',
      image: 'https://boheme.su/upload/iblock/95b/knkdxsh0ou6ps1o420u2h57vjay3hlaz.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Brilante',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для ванны',
      price: 50147.0,
      weight: 5840.0,
      width: 160.0,
      length: 260.0,
      height: 1050.0,
    },
    {
      article: '289',
      name: 'Смеситель напольный IMPERIALE',
      image: 'https://boheme.su/upload/iblock/1da/8nc86jz299i68mqmzx5f06zt4i9jlbv1.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Imperiale',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для ванны',
      price: 59027.0,
      weight: 5840.0,
      width: 160.0,
      length: 260.0,
      height: 1050.0,
    },
    {
      article: '309',
      name: 'Смеситель напольный MEDICI',
      image: 'https://boheme.su/upload/iblock/e1d/g7isqv3n2kxwd0bt6gtqhvnok05zvrf5.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Medici',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для ванны',
      price: 55893.0,
      weight: 5840.0,
      width: 160.0,
      length: 260.0,
      height: 1050.0,
    },
    {
      article: '289-SW',
      name: 'Смеситель напольный IMPERIALE с кристаллом Swarovski',
      image: 'https://boheme.su/upload/iblock/d87/3c9ok7au94gfds43vxg8aox6ylw51eqc.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Imperiale',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для ванны',
      price: 84870.0,
      weight: 0.0,
      width: 1050.0,
      length: 260.0,
      height: 160.0,
    },
    {
      article: '114-B',
      name: 'Смеситель для кухни UNO BLACK',
      image: 'https://boheme.su/upload/iblock/5a1/vzf9hhjrzfy1sk9zbi30i2kycn72kg0u.jpg',
      color: 'черный',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 27672.0,
      weight: 2400.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '114-CR',
      name: 'Смеситель для кухни UNO CHROME',
      image: 'https://boheme.su/upload/iblock/418/3ek1a2n4zilb7juj3z4yfr0mr0rpd5rd.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 25016.0,
      weight: 2400.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '114-G',
      name: 'Смеситель для кухни UNO GOLD',
      image: 'https://boheme.su/upload/iblock/89d/mf0oga87ny3xsf4i1bqa6cvyvusunkh2.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 29214.0,
      weight: 2400.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '114-GM',
      name: 'Смеситель для кухни UNO GUN METALL',
      image: 'https://boheme.su/upload/iblock/77e/m4jmifthrjprk11gyz4wyzu5ptab72sa.jpg',
      color: 'графит',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 30107.0,
      weight: 2400.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '114-MG',
      name: 'Смеситель для кухни UNO MATT GOLD',
      image: 'https://boheme.su/upload/iblock/de3/9d9a8npxoigw7cl4vgvpz325w761mnxj.jpg',
      color: 'золото-матовый',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 30107.0,
      weight: 2400.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '114-NB',
      name: 'Смеситель для кухни UNO NIKEL BRUSH',
      image: 'https://boheme.su/upload/iblock/014/06cg9f3l7drvkmjt93wsyuu1uhlfql3n.jpg',
      color: 'никель',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 29214.0,
      weight: 2400.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '114-SGM',
      name: 'Смеситель для кухни UNO Shine Gun Metal',
      image: 'https://boheme.su/upload/iblock/e83/da4owyfl55ruyxztghh728z144vnajip.jpg',
      color: 'графит глянец',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 30107.0,
      weight: 2400.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '115-B',
      name: 'Смеситель для кухни UNO BLACK c краном для питьевой воды',
      image: 'https://boheme.su/upload/iblock/f2c/j70u8f132m9e1l0sgautfuv7ol5c10wc.jpg',
      color: 'черный',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 30570.0,
      weight: 2875.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '115-CR',
      name: 'Смеситель для кухни UNO CHROME c краном для питьевой воды',
      image: 'https://boheme.su/upload/iblock/52c/wdee9layhdoqy5u3uow1daq92du3hugz.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 27914.0,
      weight: 2875.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '115-G',
      name: 'Смеситель для кухни UNO GOLD c краном для питьевой воды',
      image: 'https://boheme.su/upload/iblock/4a1/38ex5pu7aap784zcvc76fktsho5vsoa9.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 32683.0,
      weight: 2875.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '115-GM',
      name: 'Смеситель для кухни UNO GUN METALL c краном для питьевой воды',
      image: 'https://boheme.su/upload/iblock/102/wcfh1wt52s4s4sxwqv1o65b04e9nqkvk.jpg',
      color: 'графит',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 33261.0,
      weight: 2875.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '115-MG',
      name: 'Смеситель для кухни UNO MATT GOLD c краном для питьевой воды',
      image: 'https://boheme.su/upload/iblock/b5e/1m3ua5y2r9nualv04b8lox55gx9nzlwi.jpg',
      color: 'золото-матовый',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 33261.0,
      weight: 2875.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '115-NB',
      name: 'Смеситель для кухни UNO NIKEL BRUSH c краном для питьевой воды',
      image: 'https://boheme.su/upload/iblock/c43/zb54a1tv1nf3hfcdy24yi0fkhbyimk45.jpg',
      color: 'никель',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 32683.0,
      weight: 2875.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '115-SGM',
      name: 'Смеситель для кухни UNO Shine Gun Metal c краном для питьевой воды',
      image: 'https://boheme.su/upload/iblock/5b4/xyz0o0zmg50q1w3o59ikx9nqtaf8fkqf.jpg',
      color: 'графит глянец',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: '',
      style: 'современный',
      control: 'однорычажный',
      view: 'для кухни',
      price: 33890.0,
      weight: 2875.0,
      width: 55.0,
      length: 280.0,
      height: 521.0,
    },
    {
      article: '101-CRST',
      name: 'Смеситель для кухни CRYSTAL, бронза',
      image: 'https://boheme.su/upload/iblock/9b4/c0cha34wnvo1krbffv4be9f4tze4e8vu.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 38258.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 301.0,
    },
    {
      article: '101-PR',
      name: 'Смеситель для кухни MEDICI Ripresa ручка Provanse',
      image: 'https://boheme.su/upload/iblock/69f/klxxj5it5zmgbnihztpu5scf85jvw04s.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 24853.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 301.0,
    },
    {
      article: '101-SW',
      name: 'Смеситель для кухни MEDICI Ripresa с кристаллом Swarovski',
      image: 'https://boheme.su/upload/iblock/832/n6btylx4gip0y419yeg6q124xu28jrbn.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 39312.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 301.0,
    },
    {
      article: '102-BLC',
      name: 'Смеситель для кухни TRADIZIONALE ORO черная керамика',
      image: 'https://boheme.su/upload/iblock/130/ns5winlfb3a1o100bmrxymosjtsj4bwy.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 28910.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 301.0,
    },
    {
      article: '102-BSW',
      name: 'Смеситель для кухни TRADIZIONALE ORO с кристаллом Black Swarovski',
      image: 'https://boheme.su/upload/iblock/25d/xmcnjylm3tqhn1f4j9vtdxru0p6v1bts.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 44558.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 301.0,
    },
    {
      article: '102-CRST',
      name: 'Смеситель для кухни TRADIZIONALE ORO CRYSTAL',
      image: 'https://boheme.su/upload/iblock/9c3/boldj0iwf31w0tz15faofmsm30omm381.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 40870.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 301.0,
    },
    {
      article: '102-SW',
      name: 'Смеситель для кухни TRADIZIONALE ORO с кристаллом Swarovski',
      image: 'https://boheme.su/upload/iblock/38c/p9h3y3r1e5lxpp16b6otys992kw25z50.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 41923.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 301.0,
    },
    {
      article: '103-BLC',
      name: 'Смеситель для кухни TRADIZIONALE ORO, черная керамика',
      image: 'https://boheme.su/upload/iblock/d06/l0mevb6e9nd5z5h9q7ghrc2kr8n456j4.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 23686.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 301.0,
    },
    {
      article: '103-BSW',
      name: 'Смеситель для кухни TRADIZIONALE CHROMO с кристаллом BLACK Swarovski',
      image: 'https://boheme.su/upload/iblock/ce0/l3rjdgahy8d6bexvh21l2bq7phx9o2zu.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 39334.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 301.0,
    },
    {
      article: '103-CRST',
      name: 'Смеситель для кухни TRADIZIONALE CHROMO с ручкой CRISTAL',
      image: 'https://boheme.su/upload/iblock/acd/3ko1w7cjylxaj2ul84osuvp9n9ulf1lt.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 35646.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 301.0,
    },
    {
      article: '103-SW',
      name: 'Смеситель для кухни TRADIZIONALE CHROMO с кристаллом Swarovski',
      image: 'https://boheme.su/upload/iblock/b86/105nf9ptn1hjv3kzx4g3uz9s7u52wbev.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 36701.0,
      weight: 2200.0,
      width: 55.0,
      length: 220.0,
      height: 301.0,
    },
    {
      article: '111-CRST',
      name: 'Смеситель для кухни с краном MEDICI Ripresa с ручкой CRYSTAL',
      image: 'https://boheme.su/upload/iblock/587/e6a0lmsz36c4yuwskbqdjfwuq6l2ugyv.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 54838.0,
      weight: 2400.0,
      width: 55.0,
      length: 231.0,
      height: 353.0,
    },
    {
      article: '111-PR',
      name: 'Смеситель для кухни с краном MEDICI Ripresa ручки Provanse',
      image: 'https://boheme.su/upload/iblock/b8b/h9m9l9emh9ijaiqfn1qudhj3adqpoazb.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 28026.0,
      weight: 2400.0,
      width: 55.0,
      length: 231.0,
      height: 353.0,
    },
    {
      article: '111-SW',
      name: 'Смеситель для кухни с краном MEDICI Ripresa с кристаллом Swarovski',
      image: 'https://boheme.su/upload/iblock/1fe/mbz3wa5vgvokqmoyrhhfjs8vxi4zoedb.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 56946.0,
      weight: 2400.0,
      width: 55.0,
      length: 231.0,
      height: 353.0,
    },
    {
      article: '112-BLC',
      name: 'Смеситель для кухни с краном TRADIZIONALE ORO с черной керамикой',
      image: 'https://boheme.su/upload/iblock/f0b/fvv9mhj4f07pe16xfgb3w49ccoedeb1i.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 33451.0,
      weight: 2400.0,
      width: 55.0,
      length: 231.0,
      height: 353.0,
    },
    {
      article: '112-BSW',
      name: 'Смеситель для кухни с краном TRADIZIONALE ORO с черным кристаллом Swarovski',
      image: 'https://boheme.su/upload/iblock/db9/m71cm8auqemlln4prchlw3sr843kdtjp.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 64747.0,
      weight: 2400.0,
      width: 55.0,
      length: 231.0,
      height: 353.0,
    },
    {
      article: '112-CRST',
      name: 'Смеситель для кухни с краном TRADIZIONALE ORO с ручкой CRYSTAL',
      image: 'https://boheme.su/upload/iblock/03f/t3qticapi996e4ybnrgso70wx31rdsga.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 57371.0,
      weight: 2400.0,
      width: 55.0,
      length: 231.0,
      height: 353.0,
    },
    {
      article: '112-SW',
      name: 'Смеситель для кухни с краном TRADIZIONALE ORO с кристаллом Swarovski',
      image: 'https://boheme.su/upload/iblock/577/20d0h3bnkodg4k4r69laerxyk4pedi62.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 59480.0,
      weight: 2400.0,
      width: 55.0,
      length: 231.0,
      height: 353.0,
    },
    {
      article: '113-BLC',
      name: 'Смеситель для кухни с краном TRADIZIONALE CHROMO с ручкой черная керамика',
      image: 'https://boheme.su/upload/iblock/fab/ma6k15zh1sb968scmcoz1010rkrpj2fj.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 27941.0,
      weight: 2400.0,
      width: 55.0,
      length: 231.0,
      height: 353.0,
    },
    {
      article: '113-BSW',
      name: 'Смеситель для кухни с краном TRADIZIONALE CHROMO с черным кристаллом Swarovski',
      image: 'https://boheme.su/upload/iblock/521/jsndsx4oz3p41xtqw0qw2q3hqpmq45no.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 59237.0,
      weight: 2400.0,
      width: 55.0,
      length: 231.0,
      height: 353.0,
    },
    {
      article: '113-CRST',
      name: 'Смеситель для кухни с краном TRADIZIONALE CHROMO CRISTAL',
      image: 'https://boheme.su/upload/iblock/19f/3ig5y8d45ahmvpo80f2q51yx7xnmlqpu.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 51861.0,
      weight: 2400.0,
      width: 55.0,
      length: 231.0,
      height: 353.0,
    },
    {
      article: '113-SW',
      name: 'Смеситель для кухни с краном TRADIZIONALE CHROMO с кристаллом Swarovski',
      image: 'https://boheme.su/upload/iblock/1db/kgh5hn55icl8r95offx9yo7znv81urpf.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Kitchen',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для кухни',
      price: 53968.0,
      weight: 2400.0,
      width: 55.0,
      length: 233.0,
      height: 353.0,
    },
    {
      article: '134-3-GM',
      name: 'Смеситель встроенный с термостатом 3-х проходной GUN METAL',
      image: 'https://boheme.su/upload/iblock/28e/6bwd2k1e04jjov9f3u6hb7tjrlcfve4v.jpg',
      color: 'графит',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 40690.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '134-3-MG',
      name: 'Смеситель встроенный с термостатом 3-х проходной MATT GOLD',
      image: 'https://boheme.su/upload/iblock/063/t1qogk4an0597owae6vw28gjh8b7t9ps.jpg',
      color: 'золото-матовый',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 40690.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '134-3-MW',
      name: 'Смеситель встроенный с термостатом 3-х проходной MATT WHITE',
      image: 'https://boheme.su/upload/iblock/cea/5bhcnud4gw6yxd2urq9wzapxm8mljawq.jpg',
      color: 'белый',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 40690.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '134-3-NB',
      name: 'Смеситель встроенный с термостатом 3-х проходной NICKEL BRUSH',
      image: 'https://boheme.su/upload/iblock/490/9bsqy0go5wakorw2eyxa2973nlvd3pm1.jpg',
      color: 'никель',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 40690.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '134-3-SGM',
      name: 'Смеситель встроенный с термостатом 3-х проходной SHINE GUN METAL',
      image: 'https://boheme.su/upload/iblock/ba0/mu02dhevd6z18nw3b2bv7ewi55y1p1di.jpg',
      color: 'никель',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 40690.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-2-B',
      name: 'Смеситель встроенный однорычажный 2-х проходной BLACK',
      image: 'https://boheme.su/upload/iblock/4c8/vmwia7kngv7g5afm6azuajiuhcpjmyrs.jpg',
      color: 'черный',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-2-CR',
      name: 'Смеситель встроенный однорычажный 2-х проходной CHROME',
      image: 'https://boheme.su/upload/iblock/653/qbuljc7r1jdke9zhif5bh9ph8p5za6ay.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 29205.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-2-G',
      name: 'Смеситель встроенный однорычажный 2-х проходной GOLD',
      image: 'https://boheme.su/upload/iblock/821/prft0qywyne77svzevug91jy95btmjm3.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-2-GM',
      name: 'Смеситель встроенный однорычажный 2-х проходной GUN METAL',
      image: 'https://boheme.su/upload/iblock/840/35rg13mffwmqx16n3np5nshgshqvkq7k.jpg',
      color: 'графит',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-2-MG',
      name: 'Смеситель встроенный однорычажный 2-х проходной MATT GOLD',
      image: 'https://boheme.su/upload/iblock/b34/bzmxws0fcxs4hecgq6mv664i1c6jo0mp.jpg',
      color: 'золото-матовый',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-2-MW',
      name: 'Смеситель встроенный однорычажный 2-х проходной MATT WHITE',
      image: 'https://boheme.su/upload/iblock/861/hmh8fxm95bg23ph0b1hju97g2u3cbjcs.jpg',
      color: 'белый',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-2-NB',
      name: 'Смеситель встроенный однорычажный 2-х проходной NICKEL BRUSH',
      image: 'https://boheme.su/upload/iblock/1e7/rulwvwerwod8b9h31cnqiy81ukv2d7lx.jpg',
      color: 'никель',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-2-SGM',
      name: 'Смеситель встроенный однорычажный 2-х проходной SHINE GUN METAL',
      image: 'https://boheme.su/upload/iblock/ebb/98rvxsp17j9uhw020p9fcbj3mwunya35.jpg',
      color: 'никель',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-3-B',
      name: 'Смеситель встроенный однорычажный 3-х проходной BLACK',
      image: 'https://boheme.su/upload/iblock/334/01w18ccwqcfejl8jga0nftrhf1n2t06r.jpg',
      color: 'черный',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-3-CR',
      name: 'Смеситель встроенный однорычажный 3-х проходной CHROME',
      image: 'https://boheme.su/upload/iblock/ecc/s5zvpkgfq1j5cvekxlnqq62nlleilrpb.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 29205.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-3-G',
      name: 'Смеситель встроенный однорычажный 3-х проходной GOLD',
      image: 'https://boheme.su/upload/iblock/ca8/ngyc4dn03wcedeqhpyko6g3gchnqx5c1.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-3-GM',
      name: 'Смеситель встроенный однорычажный 3-х проходной GUN METAL',
      image: 'https://boheme.su/upload/iblock/c3f/8bcfc62c29fl3m3ckah4hjyw30dcwaoa.jpg',
      color: 'графит',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-3-MG',
      name: 'Смеситель встроенный однорычажный 3-х проходной MATT GOLD',
      image: 'https://boheme.su/upload/iblock/661/w3oq7f7fmnvn6f9ariglpu2osxi1s08j.jpg',
      color: 'золото-матовый',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-3-MW',
      name: 'Смеситель встроенный однорычажный 3-х проходной MATT WHITE',
      image: 'https://boheme.su/upload/iblock/ac2/lg7x1ps2cg06o7dinx0spyg7tc06d8uf.jpg',
      color: 'белый',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-3-NB',
      name: 'Смеситель встроенный однорычажный 3-х проходной NICKEL BRUSH',
      image: 'https://boheme.su/upload/iblock/d17/vqb2ed1d2imclgt68faeg9zw4vgp63gh.jpg',
      color: 'никель',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '135-3-SGM',
      name: 'Смеситель встроенный однорычажный 3-х проходной SHINE GUN METAL',
      image: 'https://boheme.su/upload/iblock/6f7/sj014k75llkgtaxc8xfb85mmglhtaacw.jpg',
      color: 'никель',
      brand: 'Boheme',
      collection: 'CELL',
      base_material: 'латунь',
      style: '',
      control: 'термостат',
      view: 'для душа',
      price: 31936.0,
      weight: 0.0,
      width: 120.0,
      length: 210.0,
      height: 65.0,
    },
    {
      article: '201',
      name: 'Смеситель для раковины Vogue бронза',
      image: 'https://boheme.su/upload/iblock/165/18d3kvajoqyvia29vapilh294xxwb0kl.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Vogue',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для раковины',
      price: 27205.0,
      weight: 1640.0,
      width: 50.0,
      length: 135.0,
      height: 164.0,
    },
    {
      article: '203',
      name: 'Смеситель для ванны Vogue бронза',
      image: 'https://boheme.su/upload/iblock/1a4/mdlb86fgocetzf36nwbw1vq1tsw5w2oo.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Vogue',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для ванны',
      price: 42088.0,
      weight: 2360.0,
      width: 212.0,
      length: 176.0,
      height: 129.0,
    },
    {
      article: '204',
      name: 'Смеситель для душа Vogue бронза',
      image: 'https://boheme.su/upload/iblock/ca6/tusl6sekj6b0xfwj56lbkcj52vgatlaf.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Vogue',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для душа',
      price: 26042.0,
      weight: 1910.0,
      width: 212.0,
      length: 157.0,
      height: 128.0,
    },
    {
      article: '211',
      name: 'Смеситель для раковины Vogue золото',
      image: 'https://boheme.su/upload/iblock/93c/tcwsedt6al2ktunnzvr59h96z9xs4xbs.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Vogue',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для раковины',
      price: 28562.0,
      weight: 1640.0,
      width: 50.0,
      length: 135.0,
      height: 164.0,
    },
    {
      article: '213',
      name: 'Смеситель для ванны Vogue золото',
      image: 'https://boheme.su/upload/iblock/547/zwif02zfqh1zzy76zn7igeis1ljlmab0.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Vogue',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для ванны',
      price: 44186.0,
      weight: 2360.0,
      width: 212.0,
      length: 176.0,
      height: 129.0,
    },
    {
      article: '214',
      name: 'Смеситель для душа Vogue золото',
      image: 'https://boheme.su/upload/iblock/5e9/zjb8vvnrzxn71l95ho45zpbqelnaxdqv.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Vogue',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для душа',
      price: 27342.0,
      weight: 1910.0,
      width: 212.0,
      length: 157.0,
      height: 128.0,
    },
    {
      article: '221',
      name: 'Смеситель для раковины Vogue хром',
      image: 'https://boheme.su/upload/iblock/79a/pcjn1hcz11x6tgif2mbwxv5jbj0rk13h.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Vogue',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для раковины',
      price: 24262.0,
      weight: 1640.0,
      width: 50.0,
      length: 135.0,
      height: 164.0,
    },
    {
      article: '223',
      name: 'Смеситель для ванны Vogue хром',
      image: 'https://boheme.su/upload/iblock/50e/k3lsfa0eqq7qkg58wn96v42io4yyrqtf.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Vogue',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для ванны',
      price: 37037.0,
      weight: 2360.0,
      width: 212.0,
      length: 176.0,
      height: 129.0,
    },
    {
      article: '224',
      name: 'Смеситель для душа Vogue хром',
      image: 'https://boheme.su/upload/iblock/340/42ijdqdyypgcyig8gnoksa04jxigneom.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Vogue',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для душа',
      price: 22848.0,
      weight: 1910.0,
      width: 212.0,
      length: 157.0,
      height: 128.0,
    },
    {
      article: '381-W',
      name: 'Смеситель для умывальника VENTURO белый + золото',
      image: 'https://boheme.su/upload/iblock/425/g9n3r9oiwjoanva98ywr0nkmcwiw2psa.jpg',
      color: 'белый',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для раковины',
      price: 22723.0,
      weight: 1500.0,
      width: 50.0,
      length: 183.0,
      height: 182.0,
    },
    {
      article: '381',
      name: 'Смеситель для умывальника VENTURO золото',
      image: 'https://boheme.su/upload/iblock/246/8cr7yc61pafyjqu1wrrhrrdcq4csvx2q.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для раковины',
      price: 20766.0,
      weight: 1500.0,
      width: 50.0,
      length: 183.0,
      height: 182.0,
    },
    {
      article: '381-B',
      name: 'Смеситель для умывальника VENTURO черный + золото',
      image: 'https://boheme.su/upload/iblock/c14/b37qmq385t9watcpi2wtpzqo125jenmw.jpg',
      color: 'черный',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для раковины',
      price: 22723.0,
      weight: 1500.0,
      width: 50.0,
      length: 183.0,
      height: 182.0,
    },
    {
      article: '382-W',
      name: 'Смеситель для умывальника высокий VENTURO белый + золото',
      image: 'https://boheme.su/upload/iblock/ccd/ok4mw2tw3j6tglx8bde0bkyf0zyjqqxv.jpg',
      color: 'белый',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для раковины',
      price: 31376.0,
      weight: 2000.0,
      width: 50.0,
      length: 234.0,
      height: 292.0,
    },
    {
      article: '382',
      name: 'Смеситель для умывальника высокий VENTURO золото',
      image: 'https://boheme.su/upload/iblock/f5f/slvkzkk5dkqgja9oqc4bbx57oxd736wy.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для раковины',
      price: 29046.0,
      weight: 2000.0,
      width: 50.0,
      length: 234.0,
      height: 292.0,
    },
    {
      article: '382-B',
      name: 'Смеситель для умывальника высокий VENTURO черный + золото',
      image: 'https://boheme.su/upload/iblock/c49/w7a2eu0fg34z4dzfujxzuvt4hpcsygsw.jpg',
      color: 'черный',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для раковины',
      price: 31376.0,
      weight: 2000.0,
      width: 50.0,
      length: 234.0,
      height: 292.0,
    },
    {
      article: '383',
      name: 'Смеситель для ванны с душ.гарнитуром VENTURO золото',
      image: 'https://boheme.su/upload/iblock/fa7/gmn4086cg0t9705119z1lxh9l3ai4jtk.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для ванны',
      price: 41518.0,
      weight: 2500.0,
      width: 210.0,
      length: 201.0,
      height: 60.0,
    },
    {
      article: '383-W',
      name: 'Смеситель для ванны с душ.гарнитуром VENTURO белый + золото',
      image: 'https://boheme.su/upload/iblock/d44/rb6kxpd8uvrg7hyy1xxejud2kvpkw0nh.jpg',
      color: 'белый',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для ванны',
      price: 40957.0,
      weight: 2500.0,
      width: 210.0,
      length: 201.0,
      height: 60.0,
    },
    {
      article: '383-B',
      name: 'Смеситель для ванны с душ.гарнитуром VENTURO черный + золото',
      image: 'https://boheme.su/upload/iblock/161/k4za4y9srmnzer19nab8u5vde1mr5oxp.jpg',
      color: 'черный',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для ванны',
      price: 40957.0,
      weight: 2500.0,
      width: 210.0,
      length: 201.0,
      height: 60.0,
    },
    {
      article: '201-CRST',
      name: 'Смеситель для умывальника VOGUE CRYSTAL, бронза_Комплект',
      image: 'https://boheme.su/upload/iblock/3f6/3qtv7ghs5i6ykx49jcx8zdyu0s3pejnr.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Vogue Crystal',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для раковины',
      price: 41960.0,
      weight: 1640.0,
      width: 50.0,
      length: 135.0,
      height: 164.0,
    },
    {
      article: '203-CRST',
      name: 'Смеситель для ванны VOGUE CRYSTAL, бронза_Комплект',
      image: 'https://boheme.su/upload/iblock/aa0/32vcosyz6ffdbu0efmyml06y25h0i3p4.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Vogue Crystal',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для ванны',
      price: 56843.0,
      weight: 2360.0,
      width: 212.0,
      length: 176.0,
      height: 129.0,
    },
    {
      article: '204-CRST',
      name: 'Смеситель для душа VOGUE CRYSTAL, бронза_Комплект',
      image: 'https://boheme.su/upload/iblock/e91/213etuw2p71b4q76houeyfvx7zh65ocp.jpg',
      color: 'бронза',
      brand: 'Boheme',
      collection: 'Vogue Crystal',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для душа',
      price: 40794.0,
      weight: 1910.0,
      width: 212.0,
      length: 157.0,
      height: 128.0,
    },
    {
      article: '221-CRST',
      name: 'Смеситель для умывальника VOGUE CRYSTAL, хром_Комплект',
      image: 'https://boheme.su/upload/iblock/c89/6hl1715s7aaxuagp1gkiun78xz0it0xo.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Vogue Crystal',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для раковины',
      price: 39018.0,
      weight: 1640.0,
      width: 50.0,
      length: 135.0,
      height: 164.0,
    },
    {
      article: '223-CRST',
      name: 'Смеситель для ванны VOGUE CRYSTAL, хром_Комплект',
      image: 'https://boheme.su/upload/iblock/e2e/tztl1nm4m8wwk46eux4exbovra4ujy2u.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Vogue Crystal',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для ванны',
      price: 51789.0,
      weight: 2360.0,
      width: 212.0,
      length: 176.0,
      height: 129.0,
    },
    {
      article: '224-CRST',
      name: 'Смеситель для душа VOGUE CRYSTAL, хром_Комплект',
      image: 'https://boheme.su/upload/iblock/c46/ie9qnf21idad321gwlpz475jt74m6hkw.jpg',
      color: 'хром',
      brand: 'Boheme',
      collection: 'Vogue Crystal',
      base_material: 'латунь',
      style: 'классический',
      control: 'однорычажный',
      view: 'для душа',
      price: 37600.0,
      weight: 1910.0,
      width: 212.0,
      length: 157.0,
      height: 128.0,
    },
    {
      article: '384-W',
      name: 'Смеситель встроенный + верхний душ + ручной душ БЕЛЫЙ+ЗОЛОТО',
      image: 'https://boheme.su/upload/iblock/e3b/j65vkalmcmhcaypi2xrcomjjqi3swyt1.jpg',
      color: 'белый',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для душа',
      price: 46816.0,
      weight: 3200.0,
      width: 250.0,
      length: 523.0,
      height: 225.0,
    },
    {
      article: '384-B',
      name: 'Смеситель встроенный + верхний душ + ручной душ ЧЕРНЫЙ+ЗОЛОТО',
      image: 'https://boheme.su/upload/iblock/7bb/8n1v56u1l07fl328q3i2lfl48kcx01mj.jpg',
      color: 'черный',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для душа',
      price: 46816.0,
      weight: 3200.0,
      width: 250.0,
      length: 523.0,
      height: 225.0,
    },
    {
      article: '384',
      name: 'Смеситель встроенный + верхний душ + ручной душ ЗОЛОТО',
      image: 'https://boheme.su/upload/iblock/ad1/cv2czgx0sxc8493aycik4juri4fjdmg2.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для душа',
      price: 51074.0,
      weight: 3200.0,
      width: 250.0,
      length: 523.0,
      height: 225.0,
    },
    {
      article: '385',
      name: 'Смеситель для умывальника из стены ЗОЛОТО',
      image: 'https://boheme.su/upload/iblock/3e8/aj9zpovv1h0w22bi1442egp4r10ct6vd.jpg',
      color: 'золото',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для раковины',
      price: 26800.0,
      weight: 2200.0,
      width: 220.0,
      length: 190.0,
      height: 100.0,
    },
    {
      article: '385-B',
      name: 'Смеситель для умывальника из стены ЧЕРНЫЙ+ЗОЛОТО',
      image: 'https://boheme.su/upload/iblock/7d9/fv8vrjc8xct2pi79c5407p9kzugqhe01.jpg',
      color: 'черный',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для раковины',
      price: 28770.0,
      weight: 2200.0,
      width: 220.0,
      length: 190.0,
      height: 100.0,
    },
    {
      article: '385-W',
      name: 'Смеситель для умывальника из стены БЕЛЫЙ+ЗОЛОТО',
      image: 'https://boheme.su/upload/iblock/1c5/ep0jjndo0yetchw310ufesl6jhgjgove.jpg',
      color: 'белый',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для раковины',
      price: 28770.0,
      weight: 2200.0,
      width: 220.0,
      length: 190.0,
      height: 100.0,
    },
    {
      article: '386-W',
      name: 'Смеситель для биде БЕЛЫЙ+ЗОЛОТО',
      image: 'https://boheme.su/upload/iblock/2c0/8xgrh6qhyu2ra5e2t2zp4hcp2p4pzybn.jpg',
      color: 'белый',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для биде',
      price: 23989.0,
      weight: 1500.0,
      width: 50.0,
      length: 160.0,
      height: 161.0,
    },
    {
      article: '386-B',
      name: 'Смеситель для биде ЧЕРНЫЙ+ЗОЛОТО',
      image: 'https://boheme.su/upload/iblock/31a/k8vhqxwb16b057ffoum7mh1ubddovjk5.jpg',
      color: 'черный',
      brand: 'Boheme',
      collection: 'Venturo',
      base_material: 'латунь',
      style: 'современный',
      control: 'однорычажный',
      view: 'для биде',
      price: 23989.0,
      weight: 1500.0,
      width: 50.0,
      length: 160.0,
      height: 161.0,
    },
  ];
  
