export type Item = {
    article: string;
    name: string;
    image? : string;
    color: string;
    brand?: string;
    collection: string;
    base_material?: string;
    style: string;
    control?: string;
    view?: string;
    price?: number;
    weight?: number;
    width?: number;
    length?: number;
    height?: number;
}

export type ItemsFromServer = Item[];

export const ITEMS: ItemsFromServer = [
    {
        article: '101',
        name: 'Смеситель для кухни MEDICI Ripresa 11111111111111111111111111111111111111111111111111111',
        image : 'https://boheme.su/upload/iblock/b29/m35xlw4na1x9itj8rh01pub69pqdnxij.jpg',
        color: 'бронза',
        brand: 'boheme',
        collection: 'Medici',
        base_material: 'латунь',
        style: 'классический',
        control: 'однорычажный',
        view: 'для кухни',
        price: 23507.00,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },
    {
        article: '102',
        name: 'Смеситель для кухни TRADIZIONALE ORO',
        image : 'https://boheme.su/upload/iblock/ed7/zvcd8nr6k5t2rfvh0lwog9uv18wmub4q.jpg',
        color: 'золото',
        brand: 'boheme',
        collection: 'Imperiale',
        base_material: 'латунь',
        style: 'классический',
        control: 'однорычажный',
        view: 'для кухни',
        price: 26118.00 ,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },

    {
        article: '103',
        name: 'Смеситель для кухни MEDICI Ripresa',
        image : 'https://boheme.su/upload/iblock/b29/m35xlw4na1x9itj8rh01pub69pqdnxij.jpg',
        color: 'бронза',
        brand: 'boheme',
        collection: 'Medici',
        base_material: 'латунь',
        style: 'классический',
        control: 'однорычажный',
        view: 'для душа',
        price: 23507.00,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },

    {
        article: '104',
        name: 'Стойка для душа со смесителем UNO белый хром',
        image : 'https://boheme.su/upload/iblock/e01/mftje4e7pgb32zj23hmf7htbgae00k2c.jpg',
        color: 'бронза',
        brand: 'boheme',
        collection: 'Kitchen',
        base_material: 'латунь',
        style: 'классический',
        control: 'однорычажный',
        view: 'для кухни',
        price: 23507.00,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },

    
    {
        article: '105',
        name: 'Смеситель для кухни MEDICI Ripresa',
        image : 'https://boheme.su/upload/iblock/e1d/g7isqv3n2kxwd0bt6gtqhvnok05zvrf5.jpg',
        color: 'бронза',
        brand: 'boheme',
        collection: 'Medici',
        base_material: 'латунь',
        style: 'классический',
        control: 'однорычажный',
        view: 'для кухни',
        price: 23507.00,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },

    
    {
        article: '106',
        name: 'Смеситель для кухни MEDICI Ripresa',
        image : 'https://boheme.su/upload/iblock/b29/m35xlw4na1x9itj8rh01pub69pqdnxij.jpg',
        color: 'бронза',
        brand: 'boheme',
        collection: 'Medici',
        base_material: 'латунь',
        style: 'классический',
        control: 'однорычажный',
        view: 'для кухни',
        price: 23507.00,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },

    
    {
        article: '107',
        name: 'Смеситель для кухни MEDICI Ripresa',
        image : 'https://boheme.su/upload/iblock/b29/m35xlw4na1x9itj8rh01pub69pqdnxij.jpg',
        color: 'бронза',
        brand: 'boheme',
        collection: 'Medici',
        base_material: 'латунь',
        style: 'классический',
        control: 'однорычажный',
        view: 'для кухни',
        price: 23507.00,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },

    
    {
        article: '108',
        name: 'Смеситель для кухни MEDICI Ripresa',
        image : 'https://boheme.su/upload/iblock/b29/m35xlw4na1x9itj8rh01pub69pqdnxij.jpg',
        color: 'бронза',
        brand: 'boheme',
        collection: 'Medici',
        base_material: 'латунь',
        style: 'классический',
        control: 'однорычажный',
        view: 'для кухни',
        price: 23507.00,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },
    {
        article: '109',
        name: 'Смеситель для кухни MEDICI Ripresa',
        image : 'https://boheme.su/upload/iblock/b29/m35xlw4na1x9itj8rh01pub69pqdnxij.jpg',
        color: 'бронза',
        brand: 'boheme',
        collection: 'Kitfefewfqetrqtchen',
        base_material: 'латунь',
        style: 'классический',
        control: 'однорычажный',
        view: 'для кухни',
        price: 23507.00,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },
    {
        article: '110',
        name: 'Смеситель для кухни MEDICI Ripresa',
        image : 'https://boheme.su/upload/iblock/b29/m35xlw4na1x9itj8rh01pub69pqdnxij.jpg',
        color: 'бронза',
        brand: 'boheme',
        collection: 'Medici',
        base_material: 'латунь',
        style: 'классический',
        control: 'современный',
        view: 'для кухни',
        price: 23507.00,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },
    {
        article: '111',
        name: 'Смеситель для кухни MEDICI Ripresa',
        image : 'https://boheme.su/upload/iblock/b29/m35xlw4na1x9itj8rh01pub69pqdnxij.jpg',
        color: 'бронза',
        brand: 'boheme',
        collection: 'Medici',
        base_material: 'латунь',
        style: 'классический',
        control: 'однорычажный',
        view: 'для кухни',
        price: 23507.00,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },
    {
        article: '112',
        name: 'Смеситель для кухни MEDICI Ripresa',
        image : 'https://boheme.su/upload/iblock/b29/m35xlw4na1x9itj8rh01pub69pqdnxij.jpg',
        color: 'бронза',
        brand: 'boheme',
        collection: 'Medici',
        base_material: 'латунь',
        style: 'классический',
        control: 'однорычажный',
        view: 'для кухни',
        price: 23507.00,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },
    {
        article: '113',
        name: 'Смеситель для кухни MEDICI Ripresa',
        image : 'https://boheme.su/upload/iblock/b29/m35xlw4na1x9itj8rh01pub69pqdnxij.jpg',
        color: 'бронза',
        brand: 'boheme',
        collection: 'Medici',
        base_material: 'латунь',
        style: 'современный',
        control: 'однорычажный',
        view: 'для кухни',
        price: 23507.00,
        weight: 2200,
        width: 55,
        length: 220,
        height: 300,
    },

    

];
